version: '3.6'

networks:
  default:
    external:
      name: network

services:
  robots-logux-proxy:
    container_name: robots-logux-proxy
    build:
      context: .
      dockerfile: ./build/nodejs/Dockerfile
    restart: 'always'
    image: registry.gitlab.com/robots-miniapp/logux-proxy:nodejs_14
    env_file: ./build/.env.list
